name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pwa-android-build-box
      
    - name: sorc3r3r/publish-docker-image
      uses: SORC3r3r/docker-publish@v1-alpha
      with:
        # GitHubs GITHUB_TOKEN
        GITHUB_TOKEN: ${{ secrets.token }}
          # Docker tag of the image
        DOCKER_TAG: pwa-android-build-box
