name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t docker.pkg.github.com/jgw96/docker-android-build-box/pwa-android-build-box:latest
      
    - name: Login
      run: docker login docker.pkg.github.com -u jgw96 ${{secrets.token}}
      
    - name: Push
      run: docker push docker.pkg.github.com/jgw96/docker-android-build-box/pwa-android-build-box:latest
     
    
